apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: 2.9.x
    registry: ghcr.io/fluxcd
  components:
    - source-controller
    - helm-controller
    - kustomize-controller
    - notification-controller
  cluster:
    type: kubernetes
